version: '3.8'

services:
  mediawiki:
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    environment:
      - COMPOSER_ALLOW_SUPERUSER
      - DbName
      - DbPassword
      - DbServer
      - DbType
      - DbUser
      - OpenIDConnectClientID
      - OpenIDConnectClientSecret
      - OpenIDConnectProviderUrl
      - RedisAddress
      - RedisPassword
      - S3BucketDomain
      - S3BucketName
      - S3Endpoint
      - S3Key
      - S3Region
      - S3Secret
      - SecretKey
      - Server
      - SiteName
      - UpgradeKey
      - php_debug_config
      - production
      - wgMultiPurgeCloudFlareApiToken
      - wgMultiPurgeCloudFlareZoneId
  mediawiki-web:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      # - html:/var/www
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mediawiki
    ports:
      - 8080:80
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork

volumes:
  html:
