version: '3.8'

services:
  mediawiki:
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    tty: true
    volumes:
      - .:/var/www

  mediawiki-web:
    image: docker-registry.wikimedia.org/dev/buster-apache2:2.0.0-s1
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    ports:
      - "${MW_DOCKER_PORT:-8080}:8080"
    volumes:
      - ./:/var/www/html/w:cached
    env_file:
      - '.env'
    environment:
      MW_LOG_DIR: /var/www/html/w/cache
