services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    environment:
      - COMPOSER_ALLOW_SUPERUSER
      - DbName
      - DbPassword
      - DbServer
      - DbType
      - DbUser
      - OpenIDConnectClientID
      - OpenIDConnectClientSecret
      - OpenIDConnectProviderUrl
      - RedisAddress
      - RedisPassword
      - S3BucketDomain
      - S3BucketName
      - S3Endpoint
      - S3Key
      - S3Region
      - S3Secret
      - SecretKey
      - Server
      - SiteName
      - UpgradeKey
      - php_debug_config
      - production
      - wgMultiPurgeCloudFlareApiToken
      - wgMultiPurgeCloudFlareZoneId
      - MEDIAWIKI_VERSION
      - MEDIAWIKI_MAJOR_VERSION
    volumes:
      - './config/LocalSettings.php:/var/www/mediawiki/LocalSettings.php'
      - 'mediawiki-app:/var/www/mediawiki'
      - 'mediawiki-uploads:/var/www/mediawiki/images'
      - 'mediawiki-cache:/var/www/mediawiki/cache'
    expose:
      - '9000'

  mediawiki-web:
    image: nginx:latest
    restart: always
    depends_on:
      - mediawiki
    volumes:
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - 'mediawiki-app:/var/www/mediawiki:ro'  # Read-only access
      - 'mediawiki-uploads:/var/www/mediawiki/images'
      - 'mediawiki-cache:/var/www/mediawiki/cache'

volumes:
  mediawiki-app:
    name: mediawiki-app
  mediawiki-uploads:
    name: mediawiki-uploads
  mediawiki-cache:
    name: mediawiki-cache
