services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'mediawiki-shared-data:/var/www/mediawiki-data'
    env_file:
      - '.env'
    environment:
      - COMPOSER_ALLOW_SUPERUSER
      - DbName
      - DbPassword
      - DbServer
      - DbType
      - DbUser
      - OpenIDConnectClientID
      - OpenIDConnectClientSecret
      - OpenIDConnectProviderUrl
      - RedisAddress
      - RedisPassword
      - S3BucketDomain
      - S3BucketName
      - S3Endpoint
      - S3Key
      - S3Region
      - S3Secret
      - SecretKey
      - Server
      - SiteName
      - UpgradeKey
      - php_debug_config
      - production
      - wgMultiPurgeCloudFlareApiToken
      - wgMultiPurgeCloudFlareZoneId
      - MEDIAWIKI_VERSION
      - MEDIAWIKI_MAJOR_VERSION

  mediawiki-web:
    image: nginx:latest
    restart: always
    volumes:
      - './nginx.template.conf:/etc/nginx/conf.d/default.conf'
      - 'mediawiki-shared-data:/var/www/mediawiki-data'
    depends_on:
      - mediawiki
volume:
  mediawiki-shared-data:
   name: mediawiki-shared-data
   external: true
