name: Postgres S3cmd Image Build

on:
  push:
    branches:
      - 'postgres-s3cmd'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: starcitizentools/postgres-s3cmd:latest,starcitizentools/postgres-s3cmd:v0.0.1
